name: Python Backend CI Pipeline

on:
  push:
    branches:
      - Development
      - Feature
      - backend-ci-pipeline

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run tests using pytest
      # - name: Run tests
      #   run: |
      #     pytest --maxfail=3 --disable-warnings -q  # Run tests and stop after 3 failures

      # Collect generated files (build artifacts)
      - name: Collect generated artifacts
        run: |
          mkdir -p artifacts
          # Collect any generated files (logs, output, etc.)
          # For example, if you have output in a directory like 'output/':
          # cp output/*.json artifacts/

      # Upload build artifacts to GitHub Actions
      - name: Upload build artifacts
        uses: actions/upload-artifact@master
        with:
          name: backend-artifacts
          path: artifacts/*  # Upload everything from the 'artifacts' folder

      # Lint code using flake8
      - name: Lint code
        run: |
          pip install flake8
          flake8 . --exit-zero  # Lint code and exit without failing the pipeline