name: Python Backend CI Pipeline

on:
  push:
    branches:
      - Development
      - Feature
      - backend-ci-pipeline

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true  # Ensure submodules (like Server) are initialized

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run flake8 and save the linting results
      - name: Run flake8 and save results
        run: |
          pip install flake8
          flake8 . --exit-zero > flake8_results.txt  # Save the flake8 results to a text file

      # Debug: Check the directory structure
      - name: Debug Directory Structure
        run: |
          pwd  # Show the current working directory
          ls -al  # List all files to make sure 'Server' is present at the right location

      # Start the server in the background
      - name: Start the server
        run: |
          cd ../Server  # Adjust the path if needed
          nohup npm run dev &  # Run server in the background
          
      # Wait for the server to start and become available (adjust time as needed)
      - name: Wait for server to start
        run: |
          sleep 10  # Wait for 10 seconds, adjust time if necessary

      - name: Check if the server is running
        run: |
          curl --silent --fail http://localhost:4000/api/unprocessedData || exit 1
        
      # Run Python tests and save the results to a text file
      - name: Run Python tests
        run: |
          pip install -r requirements.txt  # Ensure dependencies are installed
          mkdir -p test_results
          python -m unittest discover -s test -p "*.py" > test_results/test_report.txt  # Save the test results to a text file

      # Collect generated files (including flake8 results and test results)
      - name: Collect generated artifacts
        run: |
          mkdir -p artifacts
          # Move the flake8 results and test results to the artifacts folder
          mv flake8_results.txt artifacts/
          mv test_results/test_report.txt artifacts/

      # Upload build artifacts to GitHub Actions
      - name: Upload build artifacts
        uses: actions/upload-artifact@master
        with:
          name: backend-artifacts
          path: artifacts/*  # Upload everything from the 'artifacts' folder

