name: Python Backend CI Pipeline

on:
  push:
    branches:
      - Development
      - Feature
      - backend-ci-pipeline

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'  # Ensure submodules are initialized and updated

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run flake8 and save the linting results
      - name: Run flake8 and save results
        run: |
          pip install flake8
          flake8 . --exit-zero > flake8_results.txt  # Save the flake8 results to a text file

      # Debug: Check the directory structure
      - name: Debug Directory Structure
        run: |
          pwd  # Show the current working directory
          ls -al  # List all files to check if 'Server' folder exists
        
      # Run Python tests and save the results as JUnit XML
      - name: Run Python tests and save results
        run: |
          pip install -r requirements.txt  # Ensure dependencies are installed
          mkdir -p test_results
          # Run all tests in the Test folder and save the output in text format
          python -m unittest discover -s Test -p "*.py" > test_results/test_report.txt  # Run all tests and save output
          # Convert the output to JUnit XML format using pytest
          pytest --maxfail=1 --disable-warnings --junitxml=test_results/junit_report.xml

      # Collect generated files (including flake8 results, test results, and JUnit test results)
      - name: Collect generated artifacts
        run: |
          mkdir -p artifacts
          # Move the flake8 results and test results to the artifacts folder
          mv flake8_results.txt artifacts/
          mv test_results/test_report.txt artifacts/
          mv test_results/junit_report.xml artifacts/  # Upload JUnit XML test results

      # Upload build artifacts to GitHub Actions
      - name: Upload build artifacts
        uses: actions/upload-artifact@master
        with:
          name: backend-artifacts
          path: artifacts/*  # Upload everything from the 'artifacts' folder

